"""Tests for the local PDF invoice parser (STEP 2).

Uses the synthetic fixture PDF in sample_data/. The fixture is
regenerated by running make_synthetic.py.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from services.invoice_parser import (
    MAX_PDF_BYTES,
    MAX_RAW_TEXT_PREVIEW,
    InvoiceParseResult,
    parse_pdf,
    preview_text,
)


PROJECT_ROOT = Path(__file__).resolve().parents[1]
FIXTURE = (
    PROJECT_ROOT
    / "sample_data"
    / "synthetic_invoices"
    / "sample_synthetic_invoice.pdf"
)


@pytest.fixture(scope="module")
def synthetic_pdf_bytes():
    """Load the fixture PDF once per module."""
    return FIXTURE.read_bytes()


def test_parse_synthetic_pdf_succeeds(synthetic_pdf_bytes):
    """Sanity: the fixture parses cleanly."""
    result = parse_pdf(synthetic_pdf_bytes, "sample_synthetic_invoice.pdf")
    assert isinstance(result, InvoiceParseResult)
    assert result.parsing_status == "ok"
    assert result.error is None
    assert result.page_count == 1
    assert result.raw_text.strip() != ""


def test_parse_extracts_expected_strings(synthetic_pdf_bytes):
    """The fixture must contain the synthetic vendor and amounts."""
    text = parse_pdf(synthetic_pdf_bytes, "sample_synthetic_invoice.pdf").raw_text
    for needle in (
        "Rocky Mountain Drilling Services",
        "RMD-2026-001",
        "PO-1042",
        "10,000.00",
        "500.00",
        "10,500.00",
        "SYNTHETIC",
    ):
        assert needle in text, f"expected {needle!r} in parsed text"


def test_parse_rejects_non_pdf_bytes():
    """Plain bytes that are not a PDF must fail safely."""
    result = parse_pdf(b"hello world", "fake.pdf")
    assert result.parsing_status == "unsupported"
    assert result.error is not None
    assert result.page_count == 0
    assert result.raw_text == ""


def test_parse_rejects_empty_bytes():
    result = parse_pdf(b"", "empty.pdf")
    assert result.parsing_status == "empty"
    assert result.page_count == 0


def test_parse_rejects_non_bytes_input():
    result = parse_pdf("not bytes", "x.pdf")
    assert result.parsing_status == "failed"
    assert result.page_count == 0


def test_parse_filename_recorded(synthetic_pdf_bytes):
    """Original filename must be preserved."""
    r = parse_pdf(synthetic_pdf_bytes, "acme.pdf")
    assert r.filename == "acme.pdf"


def test_preview_text_short_returns_unchanged():
    """Short text must be returned verbatim."""
    s = "hello world"
    assert preview_text(s) == s
    assert preview_text(s, max_chars=999) == s


def test_preview_text_long_is_truncated_with_marker():
    long = "x" * (MAX_RAW_TEXT_PREVIEW + 500)
    out = preview_text(long)
    assert out.startswith("x" * MAX_RAW_TEXT_PREVIEW)
    assert "truncated" in out
    # Must NOT include the entire string (privacy).
    assert len(out) < len(long)


def test_preview_text_empty_returns_empty():
    assert preview_text("") == ""


def test_parse_pdf_does_not_call_network(synthetic_pdf_bytes, monkeypatch):
    """Hard guarantee: parser is offline.

    Block the actual functions that would be used to make a network call,
    without touching `socket.socket` itself (which would break ssl.py's
    SSLSocket base class).
    """
    import socket
    import urllib.request

    def _blocked_create_connection(*a, **k):
        raise AssertionError("parse_pdf must not open TCP connections")

    def _blocked_getaddrinfo(*a, **k):
        raise AssertionError("parse_pdf must not perform DNS lookups")

    def _blocked_urlopen(*a, **k):
        raise AssertionError("parse_pdf must not make HTTP requests")

    monkeypatch.setattr(socket, "create_connection", _blocked_create_connection, raising=True)
    monkeypatch.setattr(socket, "getaddrinfo", _blocked_getaddrinfo, raising=True)
    monkeypatch.setattr(urllib.request, "urlopen", _blocked_urlopen, raising=True)

    r = parse_pdf(synthetic_pdf_bytes, "sample_synthetic_invoice.pdf")
    assert r.parsing_status == "ok"


def test_max_pdf_bytes_constant_is_reasonable():
    """The cap should be > 0 and < 1 GB (sanity)."""
    assert 0 < MAX_PDF_BYTES < 1024 * 1024 * 1024
