"""OilOps AI service layer.

Services contain business logic (parsing, privacy filtering,
validation, AI classification, persistence). Each service is a plain
Python module with a small public API so it can be exercised by both
the Streamlit UI and the pytest test suite without UI-specific
dependencies.
"""
from .invoice_extractor import InvoiceExtraction, extract_invoice
from .invoice_parser import (
    InvoiceParseResult,
    MAX_PDF_BYTES,
    MAX_RAW_TEXT_PREVIEW,
    parse_pdf,
    preview_text,
)
from .privacy_filter import (
    ALL_CATEGORIES,
    CATEGORY_BANK_ACCOUNT,
    CATEGORY_EMAIL,
    CATEGORY_IBAN,
    CATEGORY_PHONE,
    CATEGORY_ROUTING_NUMBER,
    CATEGORY_SWIFT,
    Detection,
    RedactionResult,
    build_ai_safe_payload,
    is_ai_safe_payload,
    redact_text,
)
from .ai_classifier import (
    ALL_SOURCES,
    CATEGORY_EQUIPMENT,
    CATEGORY_FIELD_SERVICES,
    CATEGORY_OFFICE,
    CATEGORY_OTHER,
    CATEGORY_PROFESSIONAL_SERVICES,
    CATEGORY_TRANSPORTATION,
    CATEGORY_TRAVEL,
    ClassificationResult,
    ClassifierPayloadError,
    EXPENSE_CATEGORIES,
    LLMProvider,
    LOW_CONFIDENCE_THRESHOLD,
    MAX_REASON_LEN,
    MockProvider,
    OpenAIHTTPProvider,
    ProviderError,
    SOURCE_LLM,
    SOURCE_MOCK,
    SOURCE_RULE,
    assert_classifier_payload_safe,
    build_classifier_payload,
    classify_expense,
    format_classification_summary,
    get_provider,
    is_api_key_configured,
)
from .invoice_repository import (
    ALL_STATUSES,
    ALL_TRACKER_FILTERS,
    InvalidPaymentState,
    InvalidStateTransition,
    InvoiceRepositoryError,
    MissingReviewNoteError,
    MissingReviewerError,
    NotFoundError,
    SavedInvoice,
    STATUS_APPROVED,
    STATUS_PENDING,
    STATUS_REJECTED,
    TRACKER_FILTER_ALL,
    TRACKER_FILTER_APPROVED,
    TRACKER_FILTER_OUTSTANDING,
    TRACKER_FILTER_PAID,
    TRACKER_FILTER_PENDING,
    TRACKER_FILTER_REJECTED,
    approve_invoice,
    get_invoice,
    list_payment_tracker,
    mark_paid,
    reject_invoice,
    save_pending,
)
from .session_state import (
    compute_classifier_fingerprint,
    fingerprint_matches,
    reset_review_session,
    session_has_invoice,
)


from .dashboard_service import (
    ALLOWED_CURRENCY_FILTERS,
    CategorySpend,
    CURRENCY_FILTER_ALL,
    CurrencyAmounts,
    DashboardSnapshot,
    DuplicateGroup,
    KPICards,
    NeedsAttentionItem,
    RecentInvoice,
    VendorSpend,
    compute_dashboard,
)

# Batch 2 - Invoice Intake Queue
from .queue_status import (
    ALL_QUEUE_STATUSES,
    QUEUE_STATUS_FAILED,
    QUEUE_STATUS_NEEDS_REVIEW,
    QUEUE_STATUS_POSSIBLE_DUPLICATE,
    QUEUE_STATUS_READY,
    derive_queue_status,
    queue_status_priority,
)
from .batch_intake import (
    BATCH_MAX_PDF_BYTES,
    BatchIntakeFile,
    BatchIntakeItem,
    process_pdf_batch,
    queue_row_from_item,
)


__all__ = [
    "InvoiceExtraction",
    "extract_invoice",
    "InvoiceParseResult",
    "MAX_PDF_BYTES",
    "MAX_RAW_TEXT_PREVIEW",
    "parse_pdf",
    "preview_text",
    # Privacy filter (STEP 4)
    "ALL_CATEGORIES",
    "CATEGORY_BANK_ACCOUNT",
    "CATEGORY_ROUTING_NUMBER",
    "CATEGORY_SWIFT",
    "CATEGORY_IBAN",
    "CATEGORY_EMAIL",
    "CATEGORY_PHONE",
    "Detection",
    "RedactionResult",
    "redact_text",
    "build_ai_safe_payload",
    "is_ai_safe_payload",
    # AI classifier (STEP 6)
    "ALL_SOURCES",
    "CATEGORY_EQUIPMENT",
    "CATEGORY_FIELD_SERVICES",
    "CATEGORY_OFFICE",
    "CATEGORY_OTHER",
    "CATEGORY_PROFESSIONAL_SERVICES",
    "CATEGORY_TRANSPORTATION",
    "CATEGORY_TRAVEL",
    "ClassificationResult",
    "ClassifierPayloadError",
    "EXPENSE_CATEGORIES",
    "LLMProvider",
    "LOW_CONFIDENCE_THRESHOLD",
    "MAX_REASON_LEN",
    "MockProvider",
    "OpenAIHTTPProvider",
    "ProviderError",
    "SOURCE_LLM",
    "SOURCE_MOCK",
    "SOURCE_RULE",
    "assert_classifier_payload_safe",
    "build_classifier_payload",
    "classify_expense",
    "format_classification_summary",
    "get_provider",
    "is_api_key_configured",
    # STEP 7 - reviewed-invoice persistence & payment tracking
    "ALL_STATUSES",
    "ALL_TRACKER_FILTERS",
    "InvalidPaymentState",
    "InvalidStateTransition",
    "InvoiceRepositoryError",
    "MissingReviewNoteError",
    "MissingReviewerError",
    "NotFoundError",
    "SavedInvoice",
    "STATUS_APPROVED",
    "STATUS_PENDING",
    "STATUS_REJECTED",
    "TRACKER_FILTER_ALL",
    "TRACKER_FILTER_APPROVED",
    "TRACKER_FILTER_OUTSTANDING",
    "TRACKER_FILTER_PAID",
    "TRACKER_FILTER_PENDING",
    "TRACKER_FILTER_REJECTED",
    "approve_invoice",
    "get_invoice",
    "list_payment_tracker",
    "mark_paid",
    "reject_invoice",
    "save_pending",
    # STEP 7 - session_state helpers (anti-rerun / STEP 6 hardening)
    "compute_classifier_fingerprint",
    "fingerprint_matches",
    "reset_review_session",
    "session_has_invoice",
    # STEP 8 - Office Dashboard
    "ALLOWED_CURRENCY_FILTERS",
    "CategorySpend",
    "CURRENCY_FILTER_ALL",
    "CurrencyAmounts",
    "DashboardSnapshot",
    "DuplicateGroup",
    "KPICards",
    "NeedsAttentionItem",
    "RecentInvoice",
    "VendorSpend",
    "compute_dashboard",
    # Batch 2 - Invoice Intake Queue
    "ALL_QUEUE_STATUSES",
    "QUEUE_STATUS_FAILED",
    "QUEUE_STATUS_NEEDS_REVIEW",
    "QUEUE_STATUS_POSSIBLE_DUPLICATE",
    "QUEUE_STATUS_READY",
    "derive_queue_status",
    "queue_status_priority",
    "BATCH_MAX_PDF_BYTES",
    "BatchIntakeFile",
    "BatchIntakeItem",
    "process_pdf_batch",
    "queue_row_from_item",
]
